# 🔖 Bayesian Reasoning {#br}

<script src="files/js/dcl.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"> </script>

```{r ,include=FALSE}
tutorial::go_interactive(greedy = FALSE)

```

- **Lecture slides: **     <button class="btn btn-primary" data-toggle="collapse" data-target="#BR12">Bayesian Reasoning</button> 
<div id="BR12" class="collapse">
<embed src="https://docs.google.com/presentation/d/1gwI6y7yyqi8GWdPuS9dZlXsZs-1r1TsumQb-PL4Hu5s/edit?usp=sharing" width="100%" height="500px"></embed>
</div>

## Snippet 1: Covid Odds after positive Home Test. 

```{r,tut=TRUE,height=600}
#Belief = "Have Covid"
#Observation = Covid Test
#How much the probability of having covid increases upon positive COVID-test?
#We use the odds formulation of Bayesian Theorem
# we begin with prior odds of having Covid:  P(Covid)/(1-P(Covid)
PriorHaveCovid<-0.01
PriorCovidOdds<-PriorHaveCovid/(1-PriorHaveCovid)
PriorCovidOdds
#True positive:  Probability of having positive Covid test when having covid  = P(PositiveCovidTest|HaveCovid)
TruePositive<-0.99
#False positive = Probability of having positive Covid test when not having covid = P(PostiveCovidTest/DoNotHaveCovid)
FalsePositive<-0.001
LikelihoodRatio<-TruePositive/FalsePositive
PosteriorCovidOdds<-LikelihoodRatio*PriorCovidOdds
PosteriorHaveCovid<- PosteriorCovidOdds/(1+PosteriorCovidOdds)
PosteriorHaveCovid
```

## Snippet 2: What are the odds that an 'F' student is a freshman?

```{r,tut=TRUE,height=600}
moody<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/MoodyMarch2022b.csv')
#Belief - Student is a freshman
#Observation - Failed the class
Prior<-nrow(moody[moody$Seniority =='Freshman',])/nrow(moody)
Prior
PriorOdds<-round(Prior/(1-Prior),2)
PriorOdds
TruePositive<-round(nrow(moody[moody$Grade=='F' & moody$Seniority=='Freshman',])/nrow(
  moody[moody$Seniority =='Freshman',]),2)
TruePositive
FalsePositive<-round(nrow(moody[moody$Grade=='F'& moody$Seniority !='Freshman',])/nrow(moody[moody$Seniority !='Freshman',]),2)
FalsePositive
LikelihoodRatio<-round(TruePositive/FalsePositive,2)
LikelihoodRatio
PosteriorOdds <-LikelihoodRatio * PriorOdds
PosteriorOdds
Posterior <-PosteriorOdds/(1+PosteriorOdds)
round(Posterior,2)
```


## Snippet 3: What are the odds that a 'A' student with the score less than 80 is a psychology major?

```{r,tut=TRUE,height=600}
#Belief - what we do not know. #Is a student a psychology #major?
#Observation = what we do #know. They got an A and less #than 80 in score

moody<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/MoodyMarch2022b.csv')
Prior<-nrow(moody[moody$Major =='Psychology',])/nrow(moody)
Prior
PriorOdds<-round(Prior/(1-Prior),2)
PriorOdds
TruePositive
TruePositive<-round(nrow(moody[moody$Score <80 & moody$Grade=='A'& moody$Major=='Psychology',])/nrow(moody[moody$Major=='Psychology',]),2)
TruePositive
FalsePositive<-round(nrow(moody[moody$Score <80 & moody$Grade=='A'& moody$Major!='Psychology',])/nrow(moody[moody$Major!='Psychology',]),2)
FalsePositive
LikelihoodRatio<-round(TruePositive/FalsePositive,2)
LikelihoodRatio
PosteriorOdds <-LikelihoodRatio * PriorOdds
PosteriorOdds
Posterior <-PosteriorOdds/(1+PosteriorOdds)
Posterior
```