# 🔖 Chi Square Analysis {#chitest}

<script src="files/js/dcl.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

```{r ,include=FALSE}
tutorial::go_interactive(greedy = FALSE)

```

- **Lecture slides: **     <button class="btn btn-primary" data-toggle="collapse" data-target="#CS12">Chi Square</button> 
<div id="CS12" class="collapse">
<embed src="https://docs.google.com/presentation/d/1h-h2S5lW6ReFwdeJKNflPpE0iCjoS08T0mpgSLiFv88/edit?usp=sharing" width="100%" height="500px"></embed>
</div>

<br>

- **Great Resource: **     <a href = "https://www.khanacademy.org/math/ap-statistics/chi-square-tests/chi-square-goodness-fit/v/chi-square-statistic" target="_blank"> <button class="btn btn-primary" data-toggle="collapse" data-target="#KH12">Khan Academy</button> </a>

## Snippet 1

```{r,tut=TRUE,height=300}
Expected <-matrix(c(200,420,180, 40,120,40), nrow=3, ncol=2)
Observed<-matrix(c(200,420,180,35,120,45), nrow=3, ncol=2)
Expected
Observed
chisq.test(Observed)
```

## Snippet 2

```{r,tut=TRUE,ex="chisquarefunction",type="pre-exercise-code"}
library(dplyr)
d<-read.csv("https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/moody2022_new.csv")
head(d)

chi_test <- function(data,col1,col2,iter) {
  
  df <- data.frame(data)
  vals<- unique(df[[col2]])
  no_rows <- nrow(df)
  dt <- table(df[[col1]], df[[col2]])
  res <- chisq.test(dt)
  real_ans <- res$statistic
  ans_vec <- vector()
  for (x in 1:iter){

    new_data <- sample(x=vals,size=no_rows,replace = TRUE)

    dt_new <- table(df[[col1]], new_data)

    res_new <- chisq.test(dt_new)

    ans_vec <- append(ans_vec,res_new$statistic)
  }
  hist(ans_vec,main="Permutation Test for Chi-Square",xlab="Chi-Square Values")
  print(real_ans)
  abline(v=real_ans,col="blue",lwd=2)
}

```


```{r,tut=TRUE,ex="chisquarefunction",type="sample-code",height=500}

chi_test(d,"TEXTING_IN_CLASS","GRADE",1000)

```

## Snippet 3

```{r,tut=TRUE,height=300}
moody<-read.csv("https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/moody2022_new.csv")
moody$IN<-'Out_Slice'
moody[moody$DOZES_OFF=='never' & moody$TEXTING_IN_CLASS=='always', ]$IN<-'In_Slice'
d<-table(moody$GRADE, moody$IN)
d
chisq.test(d)
```

## Snippet 4


```{r,tut=TRUE,height=300}
movies<-read.csv("https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Movies2022F-4.csv")
data<-table(movies$content, movies$genre)
chisq.test(data)
```

