# Table

<script src="files/js/dcl.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

```{r ,include=FALSE}
tutorial::go_interactive( greedy = FALSE)

```

- **table()** displays frequency distribution of its arguments. 

<!--
- Tables (i.e. frequency distribution table) can be created using **table()** along with some of its variations. 
- To use **table()**, simply add in the variables you want to tabulate separated by a comma. 
- You must reference the variable using **dataset$variable**. 
- By default, missing values are excluded from the counts; if you want a count for these missing values you must specify the argument **useNA=“ifany”** or **useNA=“always”**. -->

The below examples show how to use this function.
```{r, tut=TRUE,height=500}
# moody<-read.csv("../files/dataset/moody2020b.csv") #static Load
moody<-read.csv("https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/moody2020b.csv") #web load

#lets make a table for the grades of students and counts of students for each Grade. 
grades <- table(moody$grade)

#lets see the above frequency distrbuted tables
grades
```