# z-test {#ztest}

<script src="files/js/dcl.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

```{r ,include=FALSE}
tutorial::go_interactive(greedy = FALSE)

```

- **Lecture slides: **     <button class="btn btn-primary" data-toggle="collapse" data-target="#HPT12">Hypothesis Testing</button> <button class="btn btn-primary" data-toggle="collapse" data-target="#CLT12">Central Limit Theorem</button>
<div id="HPT12" class="collapse">
<embed src="https://docs.google.com/presentation/d/17zX82imn7S3_r9Uls3pqInIwdPx1NIQW-O22ynSa9Sg/edit?usp=sharing" width="100%" height="500px"></embed>
</div>
<div id="CLT12" class="collapse">
<embed src="https://docs.google.com/presentation/d/15VRfffVukRxQ8V9Oh_KRG8T7dIuPjlXaYySdcqvXryQ/edit?usp=sharing" width="100%" height="500px"></embed>
</div>

<br>

- **Great Resource: **     <a href = "https://www.khanacademy.org/math/statistics-probability/significance-tests-confidence-intervals-two-samples/comparing-two-means/v/hypothesis-test-for-difference-of-means"> <button class="btn btn-primary" data-toggle="collapse" data-target="#KH12">Khan Academy</button> </a>


## Snippet 1

Lets look at the summary of traffic dartaset:

```{r,tut=TRUE,height=300}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#gives us the statistics
summary(TRAFFIC) 

```

## Snippet 2


```{r,tut=TRUE,height=800}
Traffic<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

colnames(Traffic)

# Get mean of volumes per minute
meanTunnel<-mean(Traffic$VOLUME_PER_MINUTE)

# Get standard deviation
sdTunnel<-sd(Traffic$VOLUME_PER_MINUTE)
sdTunnel

# plot histogram 
hist(Traffic$VOLUME_PER_MINUTE, breaks=100)

# Get the z-value
zeta <- (20 - meanTunnel)/sdTunnel
zeta

plot(x=seq(from = -5, to= 5, by=0.1),y=dnorm(seq(from = -5, to= 5,  by=0.1),mean=0),type='l',xlab = 'mean',  ylab='possibility')
abline(v=zeta, col='red')

# Compute P-value
p<-pnorm(zeta)
p
```

## Snippet 3 

```{r,tut=TRUE,height=800}
Traffic<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

colnames(Traffic)

# Get mean of volumes per minute
meanTunnel<-mean(Traffic$VOLUME_PER_MINUTE)
meanTunnel

# Get standard deviation
sdTunnel<-sd(Traffic$VOLUME_PER_MINUTE)
sdTunnel

# Get the z-value
zeta <- (20 - meanTunnel)/sdTunnel
zeta

plot(x=seq(from = -5, to= 5, by=0.1),y=dnorm(seq(from = -5, to= 5,  by=0.1),mean=0),type='l',xlab = 'mean',  ylab='possibility')
abline(v=zeta, col='red')

# Compute P-value
#p<-1-pnorm(zeta)
#p
p<-pnorm(zeta)
p
```

## Snippet 4

```{r,tut=TRUE,height=400}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#data clean and subset, either
lincoln.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Lincoln")
holland.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Holland")

#traffic at lincoln
#This variable is a column of 1401 rows.
lincoln.traffic <- lincoln.data$VOLUME_PER_MINUTE
head(lincoln.traffic)

#traffic at holland
#This variable is a column of 1401 rows.
holland.traffic <- holland.data$VOLUME_PER_MINUTE
head(holland.traffic)
```

## Snippet 5

```{r,tut=TRUE,height=500}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#data clean and subset, either
lincoln.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Lincoln")
holland.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Holland")

#traffic at lincoln
lincoln.traffic <- lincoln.data$VOLUME_PER_MINUTE

#traffic at holland
holland.traffic <- holland.data$VOLUME_PER_MINUTE
 
# standard deviation of two samples.
#The final value is the standard deviation, in Volume per minute.
 
sd.lincoln <- sd(lincoln.traffic)
sd.holland <- sd(holland.traffic)

sd.lincoln
sd.holland
```

## Snippet 6

```{r,tut=TRUE,height=500}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#data clean and subset, either
lincoln.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Lincoln")
holland.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Holland")

#traffic at lincoln
lincoln.traffic <- lincoln.data$VOLUME_PER_MINUTE

#traffic at holland
holland.traffic <- holland.data$VOLUME_PER_MINUTE

#means of two samples
mean.lincoln <- mean(lincoln.traffic)
mean.holland <- mean(holland.traffic)

mean.lincoln
mean.holland

#length of lincoln and holland
len_lincoln <- length(lincoln.traffic)
len_holland <- length(holland.traffic)

len_lincoln
len_holland
```

## Snippet 7

```{r,tut=TRUE,height=500}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#data clean and subset, either
lincoln.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Lincoln")
holland.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Holland")

#traffic at lincoln
lincoln.traffic <- lincoln.data$VOLUME_PER_MINUTE

#traffic at holland
holland.traffic <- holland.data$VOLUME_PER_MINUTE

# standard deviation of two samples.
sd.lincoln <- sd(lincoln.traffic)
sd.holland <- sd(holland.traffic)

#length of lincoln and holland
len_lincoln <- length(lincoln.traffic)
len_holland <- length(holland.traffic)

#standard deviation of difference traffic
sd.lin.hol <- sqrt(sd.lincoln^2/len_lincoln + sd.holland^2/len_holland)

sd.lin.hol
```

## Snippet 8

```{r,tut=TRUE,height=700}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#data clean and subset, either
lincoln.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Lincoln")
holland.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Holland")

#traffic at lincoln
lincoln.traffic <- lincoln.data$VOLUME_PER_MINUTE

#traffic at holland
holland.traffic <- holland.data$VOLUME_PER_MINUTE

# standard deviation of two samples.
sd.lincoln <- sd(lincoln.traffic)
sd.holland <- sd(holland.traffic)

#length of lincoln and holland
len_lincoln <- length(lincoln.traffic)
len_holland <- length(holland.traffic)

#standard deviation of difference traffic
sd.lin.hol <- sqrt(sd.lincoln^2/len_lincoln + sd.holland^2/len_holland)

#means of two samples
mean.lincoln <- mean(lincoln.traffic)
mean.holland <- mean(holland.traffic)

#z score
zeta <- (mean.lincoln - mean.holland)/sd.lin.hol

zeta
```

## Snippet 9

```{r,tut=TRUE,height=800}

TRAFFIC<-read.csv('https://raw.githubusercontent.com/dev7796/data101_tutorial/main/files/dataset/Traffic2022.csv')

#data clean and subset, either
lincoln.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Lincoln")
holland.data <- subset(TRAFFIC, TRAFFIC$TUNNEL == "Holland")

#traffic at lincoln
lincoln.traffic <- lincoln.data$VOLUME_PER_MINUTE

#traffic at holland
holland.traffic <- holland.data$VOLUME_PER_MINUTE

# standard deviation of two samples.
sd.lincoln <- sd(lincoln.traffic)
sd.holland <- sd(holland.traffic)

#length of lincoln and holland
len_lincoln <- length(lincoln.traffic)
len_holland <- length(holland.traffic)

#standard deviation of difference traffic
sd.lin.hol <- sqrt(sd.lincoln^2/len_lincoln + sd.holland^2/len_holland)

#means of two samples
mean.lincoln <- mean(lincoln.traffic)
mean.holland <- mean(holland.traffic)

#z score
zeta <- (mean.lincoln - mean.holland)/sd.lin.hol

#plot red line
plot(x=seq(from = -5, to= 5, by=0.1),y=dnorm(seq(from = -5, to= 5,  by=0.1),mean=0),type='l',xlab = 'mean difference',  ylab='possibility')
abline(v=zeta, col='red')

#get p
p = 1-pnorm(zeta)
p
```


